export let products = [
  {
    title: "Soga",
    price: 2500,
    stock: 3,
    description: "La soga de 2 nudos par el juego de tire-afloje",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514546/Soga-2-nudos-2_uzvp6n.png",
  },
  {
    title: "Huesos",
    price: 3000,
    stock: 3,
    description: "Huesos para morder y reducir el estres",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514433/huesos_jtsdnm.jpg",
  },
  {
    title: "Freesbe",
    price: 3000,
    stock: 5,
    description: "El mejor juego entre vos y tu perro",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514400/freesbe_j8ek6e.jpg",
  },
  {
    title: "Kongo",
    price: 6000,
    stock: 2,
    description: "Juego interactivo para tu perro mientras no estas en casa",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514453/kong_yndccy.jpg",
  },
  {
    title: "Cama",
    price: 10000,
    stock: 3,
    description: "Cama antiestress para el mejor descanso",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514375/cama_sju4cw.jpg",
  },
  {
    title: "Pretal",
    price: 9000,
    stock: 4,
    description: "Correa y pretal para mayor seguridad al salir de casa",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514497/pretales_z94ju1.jpg",
  },
  {
    title: "Ropa",
    price: 12000,
    stock: 2,
    description: "Ropa para que este mas canchero",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514535/ropa-disney_icuxgq.jpg",
  },
  {
    title: "Pretal",
    price: 9000,
    stock: 4,
    description: "Correa y pretal para mayor seguridad al salir de casa",
    category: "perros",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514497/pretales_z94ju1.jpg",
  },
  {
    title: "Set de varita con ratones",
    price: 3500,
    stock: 3,
    description: "Set intercambiable con distintos modelos",
    category: "gatos",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514527/ratoncito_isks3k.jpg",
  },
  {
    title: "Rascador",
    price: 4000,
    stock: 4,
    description: "Rascador para limar las uñas",
    category: "gatos",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514519/rascador1_tdaxgb.jpg",
  },
  {
    title: "Pretal y correa",
    price: 6000,
    stock: 2,
    description: "Pretal con correa para salir a pasear",
    category: "gatos",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514507/pretales-gato_ojwogk.jpg",
  },
  {
    title: "Juego interactivo",
    price: 4500,
    stock: 3,
    description: "Juego interactivo para reducir la ansiedad",
    category: "gatos",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514447/interactivo_vapaqo.jpg",
  },
  {
    title: "Cucha",
    price: 7500,
    stock: 3,
    description: "Casita para que descanse tu mejor amigo",
    category: "gatos",
    img: "https://res.cloudinary.com/dpzoqa2gm/image/upload/v1695514390/cama-cueva-gatos-z_giom3s.jpg",
  },
];
